import React, { useState, useRef } from 'react';
import MaterialTable from 'material-table';
import { Modal } from '@material-ui/core';
import { Link, useLocation } from 'react-router-dom';
import { MdArrowBack } from 'react-icons/md';

import {
  GridActions,
  Actions,
  LinkMore,
  Container,
  ModalContent,
  ModalTitle,
  ModalActions,
  ModalDesc,
  ModalInput,
  ModalCancel,
  ModalConfirm,
  BackLink,
} from './styles';

export default function Contact() {
  const [selected, setSelected] = useState(false);
  const [open, setOpen] = useState(false);
  const [groupCreate, setGroupCreate] = useState(false);
  const [dataContacts, setDataContacts] = useState([
    {
      id: 1,
      nome: 'Oby',
      telefone: '(414) 5624131',
      data_de_nascimento: '24/03/2020',
      genero: 'Male',
      bairro: 'WI',
      celular: '(540) 1659740',
      cad_unico: '8472336832',
      rua: '31800 Russell Terrace',
      cidade: 'Milwaukee',
      estado: 'Wisconsin',
      aspecto_familiar:
        'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    },
    {
      id: 2,
      nome: 'Vivyanne',
      telefone: '(626) 7002608',
      data_de_nascimento: '05/12/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(334) 5209651',
      cad_unico: '2136692054',
      rua: '2 Washington Hill',
      cidade: 'Los Angeles',
      estado: 'California',
      aspecto_familiar:
        'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
    },
    {
      id: 3,
      nome: 'Blakeley',
      telefone: '(432) 4376668',
      data_de_nascimento: '11/01/2020',
      genero: 'Female',
      bairro: 'TX',
      celular: '(310) 7175836',
      cad_unico: '8163501014',
      rua: '678 Arapahoe Trail',
      cidade: 'Midland',
      estado: 'Texas',
      aspecto_familiar:
        'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',
    },
    {
      id: 4,
      nome: 'Zaccaria',
      telefone: '(415) 6252999',
      data_de_nascimento: '03/11/2019',
      genero: 'Male',
      bairro: 'CA',
      celular: '(202) 6291458',
      cad_unico: '7314286744',
      rua: '46115 Hayes Hill',
      cidade: 'San Francisco',
      estado: 'California',
      aspecto_familiar:
        'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.',
    },
    {
      id: 5,
      nome: 'Myrwyn',
      telefone: '(601) 9077101',
      data_de_nascimento: '18/07/2019',
      genero: 'Male',
      bairro: 'MS',
      celular: '(254) 3417552',
      cad_unico: '4324493936',
      rua: '503 Butterfield Crossing',
      cidade: 'Hattiesburg',
      estado: 'Mississippi',
      aspecto_familiar:
        'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    },
    {
      id: 6,
      nome: 'Diahann',
      telefone: '(913) 2458999',
      data_de_nascimento: '14/09/2019',
      genero: 'Female',
      bairro: 'KS',
      celular: '(312) 8126623',
      cad_unico: '8980768478',
      rua: '6 Butternut Alley',
      cidade: 'Kansas City',
      estado: 'Kansas',
      aspecto_familiar: 'Nulla facilisi.',
    },
    {
      id: 7,
      nome: 'Nydia',
      telefone: '(646) 7110366',
      data_de_nascimento: '05/01/2020',
      genero: 'Female',
      bairro: 'NY',
      celular: '(704) 6790297',
      cad_unico: '1814266518',
      rua: '70574 Ronald Regan Junction',
      cidade: 'New York City',
      estado: 'New York',
      aspecto_familiar:
        'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    },
    {
      id: 8,
      nome: 'Yule',
      telefone: '(212) 4570508',
      data_de_nascimento: '10/03/2020',
      genero: 'Male',
      bairro: 'NY',
      celular: '(240) 3061828',
      cad_unico: '6873649414',
      rua: '5 Anderson Point',
      cidade: 'New York City',
      estado: 'New York',
      aspecto_familiar:
        'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
    },
    {
      id: 9,
      nome: 'Idalina',
      telefone: '(626) 3465526',
      data_de_nascimento: '12/04/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(216) 1717358',
      cad_unico: '7839619819',
      rua: '51434 Toban Road',
      cidade: 'Whittier',
      estado: 'California',
      aspecto_familiar:
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    },
    {
      id: 10,
      nome: 'Ogdan',
      telefone: '(202) 7570481',
      data_de_nascimento: '08/02/2020',
      genero: 'Male',
      bairro: 'DC',
      celular: '(214) 2600431',
      cad_unico: '0463090047',
      rua: '11543 Union Terrace',
      cidade: 'Washington',
      estado: 'District of Columbia',
      aspecto_familiar:
        'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.',
    },
    {
      id: 11,
      nome: 'Wolfy',
      telefone: '(505) 5971801',
      data_de_nascimento: '23/02/2020',
      genero: 'Male',
      bairro: 'NM',
      celular: '(716) 4870783',
      cad_unico: '3844257780',
      rua: '322 Chive Terrace',
      cidade: 'Santa Fe',
      estado: 'New Mexico',
      aspecto_familiar:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    },
    {
      id: 12,
      nome: 'Veronike',
      telefone: '(406) 9362323',
      data_de_nascimento: '02/01/2020',
      genero: 'Female',
      bairro: 'MT',
      celular: '(714) 7395212',
      cad_unico: '2444847555',
      rua: '8 Fallview Parkway',
      cidade: 'Helena',
      estado: 'Montana',
      aspecto_familiar:
        'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
    },
    {
      id: 13,
      nome: 'Corie',
      telefone: '(212) 6775661',
      data_de_nascimento: '03/12/2019',
      genero: 'Female',
      bairro: 'NY',
      celular: '(904) 4787878',
      cad_unico: '4217643691',
      rua: '94317 Valley Edge Way',
      cidade: 'New York City',
      estado: 'New York',
      aspecto_familiar:
        'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.',
    },
    {
      id: 14,
      nome: 'Leeland',
      telefone: '(253) 4836193',
      data_de_nascimento: '26/09/2019',
      genero: 'Male',
      bairro: 'WA',
      celular: '(413) 1796176',
      cad_unico: '0561907080',
      rua: '85 Carioca Way',
      cidade: 'Olympia',
      estado: 'Washington',
      aspecto_familiar:
        'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    },
    {
      id: 15,
      nome: 'Ede',
      telefone: '(937) 6669886',
      data_de_nascimento: '20/04/2019',
      genero: 'Female',
      bairro: 'OH',
      celular: '(713) 4161702',
      cad_unico: '4641281718',
      rua: '865 Moland Way',
      cidade: 'Dayton',
      estado: 'Ohio',
      aspecto_familiar:
        'Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
    },
    {
      id: 16,
      nome: 'Regan',
      telefone: '(205) 7100195',
      data_de_nascimento: '10/11/2019',
      genero: 'Male',
      bairro: 'AL',
      celular: '(210) 7936281',
      cad_unico: '5629761730',
      rua: '10 Havey Street',
      cidade: 'Birmingham',
      estado: 'Alabama',
      aspecto_familiar:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    },
    {
      id: 17,
      nome: 'Bing',
      telefone: '(513) 7243397',
      data_de_nascimento: '16/12/2019',
      genero: 'Male',
      bairro: 'OH',
      celular: '(816) 3180090',
      cad_unico: '9973190173',
      rua: '80 Esch Parkway',
      cidade: 'Cincinnati',
      estado: 'Ohio',
      aspecto_familiar:
        'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
    },
    {
      id: 18,
      nome: 'Gregorius',
      telefone: '(919) 3099145',
      data_de_nascimento: '28/05/2019',
      genero: 'Male',
      bairro: 'NC',
      celular: '(760) 5628625',
      cad_unico: '5407977524',
      rua: '943 Kropf Junction',
      cidade: 'Raleigh',
      estado: 'North Carolina',
      aspecto_familiar:
        'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    },
    {
      id: 19,
      nome: 'Virgilio',
      telefone: '(952) 3087383',
      data_de_nascimento: '20/10/2019',
      genero: 'Male',
      bairro: 'MN',
      celular: '(806) 8551520',
      cad_unico: '6466117243',
      rua: '4 Main Trail',
      cidade: 'Minneapolis',
      estado: 'Minnesota',
      aspecto_familiar:
        'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.',
    },
    {
      id: 20,
      nome: 'Vannie',
      telefone: '(323) 2635644',
      data_de_nascimento: '25/11/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(757) 4082097',
      cad_unico: '5283847578',
      rua: '42968 Upham Plaza',
      cidade: 'Los Angeles',
      estado: 'California',
      aspecto_familiar:
        'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    },
    {
      id: 21,
      nome: 'Christiane',
      telefone: '(501) 5611650',
      data_de_nascimento: '23/09/2019',
      genero: 'Female',
      bairro: 'AR',
      celular: '(706) 2581897',
      cad_unico: '6478923754',
      rua: '96 Clove Place',
      cidade: 'Little Rock',
      estado: 'Arkansas',
      aspecto_familiar:
        'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    },
    {
      id: 22,
      nome: 'Khalil',
      telefone: '(619) 7112043',
      data_de_nascimento: '07/04/2019',
      genero: 'Male',
      bairro: 'CA',
      celular: '(402) 3448770',
      cad_unico: '9706859063',
      rua: '548 Talisman Terrace',
      cidade: 'San Diego',
      estado: 'California',
      aspecto_familiar: 'Nulla tempus.',
    },
    {
      id: 23,
      nome: 'Orly',
      telefone: '(614) 4913587',
      data_de_nascimento: '11/01/2020',
      genero: 'Female',
      bairro: 'OH',
      celular: '(772) 4403924',
      cad_unico: '4398289046',
      rua: '0025 Division Park',
      cidade: 'Columbus',
      estado: 'Ohio',
      aspecto_familiar:
        'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
    },
    {
      id: 24,
      nome: 'Curcio',
      telefone: '(712) 3812462',
      data_de_nascimento: '20/01/2020',
      genero: 'Male',
      bairro: 'IA',
      celular: '(956) 4492833',
      cad_unico: '2626665487',
      rua: '6427 Mallory Avenue',
      cidade: 'Sioux City',
      estado: 'Iowa',
      aspecto_familiar:
        'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',
    },
    {
      id: 25,
      nome: 'Fletcher',
      telefone: '(734) 1637910',
      data_de_nascimento: '25/02/2020',
      genero: 'Male',
      bairro: 'MI',
      celular: '(262) 7356681',
      cad_unico: '9413404712',
      rua: '3 Del Mar Avenue',
      cidade: 'Detroit',
      estado: 'Michigan',
      aspecto_familiar:
        'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.',
    },
    {
      id: 26,
      nome: 'Salaidh',
      telefone: '(626) 7397117',
      data_de_nascimento: '07/08/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(702) 3836991',
      cad_unico: '5184163484',
      rua: '22 Lotheville Pass',
      cidade: 'Los Angeles',
      estado: 'California',
      aspecto_familiar:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    },
    {
      id: 27,
      nome: 'Denver',
      telefone: '(330) 7260719',
      data_de_nascimento: '27/09/2019',
      genero: 'Male',
      bairro: 'OH',
      celular: '(515) 6237144',
      cad_unico: '3650793962',
      rua: '91323 Luster Lane',
      cidade: 'Youngstown',
      estado: 'Ohio',
      aspecto_familiar:
        'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    },
    {
      id: 28,
      nome: 'Roscoe',
      telefone: '(228) 8066374',
      data_de_nascimento: '30/10/2019',
      genero: 'Male',
      bairro: 'MS',
      celular: '(714) 5444103',
      cad_unico: '4975221454',
      rua: '4 Bunker Hill Circle',
      cidade: 'Biloxi',
      estado: 'Mississippi',
      aspecto_familiar:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
    },
    {
      id: 29,
      nome: 'Lizabeth',
      telefone: '(601) 2900988',
      data_de_nascimento: '16/12/2019',
      genero: 'Female',
      bairro: 'MS',
      celular: '(859) 6757530',
      cad_unico: '2517568642',
      rua: '8 Grayhawk Crossing',
      cidade: 'Meridian',
      estado: 'Mississippi',
      aspecto_familiar:
        'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
    },
    {
      id: 30,
      nome: 'Lenette',
      telefone: '(210) 9899624',
      data_de_nascimento: '16/04/2019',
      genero: 'Female',
      bairro: 'TX',
      celular: '(318) 7065508',
      cad_unico: '3267904625',
      rua: '83 Katie Center',
      cidade: 'San Antonio',
      estado: 'Texas',
      aspecto_familiar:
        'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.',
    },
    {
      id: 31,
      nome: 'Tedi',
      telefone: '(318) 2568560',
      data_de_nascimento: '02/11/2019',
      genero: 'Female',
      bairro: 'LA',
      celular: '(801) 3473547',
      cad_unico: '7281686102',
      rua: '8599 Farmco Park',
      cidade: 'Shreveport',
      estado: 'Louisiana',
      aspecto_familiar:
        'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    },
    {
      id: 32,
      nome: 'Dion',
      telefone: '(402) 8481317',
      data_de_nascimento: '12/03/2020',
      genero: 'Male',
      bairro: 'NE',
      celular: '(215) 1784790',
      cad_unico: '3015029916',
      rua: '5801 Truax Street',
      cidade: 'Omaha',
      estado: 'Nebraska',
      aspecto_familiar:
        'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',
    },
    {
      id: 33,
      nome: 'Brucie',
      telefone: '(714) 1413451',
      data_de_nascimento: '29/01/2020',
      genero: 'Male',
      bairro: 'CA',
      celular: '(315) 4784374',
      cad_unico: '6418163397',
      rua: '83 Marcy Crossing',
      cidade: 'Anaheim',
      estado: 'California',
      aspecto_familiar:
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.',
    },
    {
      id: 34,
      nome: 'Julienne',
      telefone: '(260) 9661308',
      data_de_nascimento: '26/08/2019',
      genero: 'Female',
      bairro: 'IN',
      celular: '(202) 9376507',
      cad_unico: '6552366337',
      rua: '02301 Transport Plaza',
      cidade: 'Fort Wayne',
      estado: 'Indiana',
      aspecto_familiar:
        'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    },
    {
      id: 35,
      nome: 'Perri',
      telefone: '(615) 8625314',
      data_de_nascimento: '27/12/2019',
      genero: 'Female',
      bairro: 'TN',
      celular: '(915) 9463225',
      cad_unico: '8471327392',
      rua: '2 Summit Circle',
      cidade: 'Nashville',
      estado: 'Tennessee',
      aspecto_familiar:
        'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
    },
    {
      id: 36,
      nome: 'Maryrose',
      telefone: '(408) 8943653',
      data_de_nascimento: '05/05/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(859) 9278328',
      cad_unico: '3228681831',
      rua: '1 Elka Avenue',
      cidade: 'San Jose',
      estado: 'California',
      aspecto_familiar:
        'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
    },
    {
      id: 37,
      nome: 'Shurlocke',
      telefone: '(619) 9148458',
      data_de_nascimento: '10/02/2020',
      genero: 'Male',
      bairro: 'CA',
      celular: '(916) 3474757',
      cad_unico: '8027434955',
      rua: '6 Rutledge Terrace',
      cidade: 'San Diego',
      estado: 'California',
      aspecto_familiar:
        'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',
    },
    {
      id: 38,
      nome: 'Ritchie',
      telefone: '(313) 9296854',
      data_de_nascimento: '27/07/2019',
      genero: 'Male',
      bairro: 'MI',
      celular: '(360) 3940837',
      cad_unico: '1884960669',
      rua: '6 Miller Court',
      cidade: 'Detroit',
      estado: 'Michigan',
      aspecto_familiar:
        'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    },
    {
      id: 39,
      nome: 'Meyer',
      telefone: '(626) 8944372',
      data_de_nascimento: '02/03/2020',
      genero: 'Male',
      bairro: 'CA',
      celular: '(425) 6724941',
      cad_unico: '4965808754',
      rua: '2454 Anhalt Drive',
      cidade: 'Los Angeles',
      estado: 'California',
      aspecto_familiar: 'Vivamus tortor.',
    },
    {
      id: 40,
      nome: 'Stanislaus',
      telefone: '(405) 4606374',
      data_de_nascimento: '03/04/2020',
      genero: 'Male',
      bairro: 'OK',
      celular: '(760) 6595591',
      cad_unico: '7242046068',
      rua: '36818 Meadow Vale Way',
      cidade: 'Oklahoma City',
      estado: 'Oklahoma',
      aspecto_familiar:
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    },
    {
      id: 41,
      nome: 'Tadeas',
      telefone: '(817) 3130774',
      data_de_nascimento: '19/12/2019',
      genero: 'Male',
      bairro: 'TX',
      celular: '(770) 4585030',
      cad_unico: '8230867712',
      rua: '06 Grayhawk Circle',
      cidade: 'Arlington',
      estado: 'Texas',
      aspecto_familiar:
        'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    },
    {
      id: 42,
      nome: 'Eric',
      telefone: '(971) 1396970',
      data_de_nascimento: '28/02/2020',
      genero: 'Male',
      bairro: 'OR',
      celular: '(205) 3741879',
      cad_unico: '7728481509',
      rua: '296 Heffernan Plaza',
      cidade: 'Portland',
      estado: 'Oregon',
      aspecto_familiar: 'Morbi quis tortor id nulla ultrices aliquet.',
    },
    {
      id: 43,
      nome: 'Inna',
      telefone: '(480) 9871182',
      data_de_nascimento: '08/12/2019',
      genero: 'Female',
      bairro: 'AZ',
      celular: '(910) 1283282',
      cad_unico: '0527328502',
      rua: '8 Linden Hill',
      cidade: 'Phoenix',
      estado: 'Arizona',
      aspecto_familiar:
        'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.',
    },
    {
      id: 44,
      nome: 'Mercie',
      telefone: '(571) 9973191',
      data_de_nascimento: '30/11/2019',
      genero: 'Female',
      bairro: 'VA',
      celular: '(309) 7392104',
      cad_unico: '4416956150',
      rua: '125 Portage Way',
      cidade: 'Arlington',
      estado: 'Virginia',
      aspecto_familiar:
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',
    },
    {
      id: 45,
      nome: 'Clarie',
      telefone: '(202) 4851432',
      data_de_nascimento: '16/12/2019',
      genero: 'Female',
      bairro: 'DC',
      celular: '(251) 5922576',
      cad_unico: '5683443113',
      rua: '7241 Westridge Park',
      cidade: 'Washington',
      estado: 'District of Columbia',
      aspecto_familiar:
        'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    },
    {
      id: 46,
      nome: 'Kirby',
      telefone: '(240) 7187690',
      data_de_nascimento: '25/02/2020',
      genero: 'Male',
      bairro: 'MD',
      celular: '(915) 4892620',
      cad_unico: '5895164730',
      rua: '0702 Saint Paul Parkway',
      cidade: 'Gaithersburg',
      estado: 'Maryland',
      aspecto_familiar:
        'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    },
    {
      id: 47,
      nome: 'Deck',
      telefone: '(404) 5175350',
      data_de_nascimento: '03/05/2019',
      genero: 'Male',
      bairro: 'GA',
      celular: '(505) 3286521',
      cad_unico: '6620137989',
      rua: '8246 Marquette Crossing',
      cidade: 'Atlanta',
      estado: 'Georgia',
      aspecto_familiar:
        'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    },
    {
      id: 48,
      nome: 'Hilliary',
      telefone: '(702) 1205647',
      data_de_nascimento: '17/12/2019',
      genero: 'Female',
      bairro: 'NV',
      celular: '(330) 1467187',
      cad_unico: '2766915427',
      rua: '1364 Anniversary Avenue',
      cidade: 'Las Vegas',
      estado: 'Nevada',
      aspecto_familiar:
        'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.',
    },
    {
      id: 49,
      nome: 'Kristien',
      telefone: '(202) 8225356',
      data_de_nascimento: '29/04/2019',
      genero: 'Female',
      bairro: 'DC',
      celular: '(405) 1918973',
      cad_unico: '2474625577',
      rua: '6 Bobwhite Circle',
      cidade: 'Washington',
      estado: 'District of Columbia',
      aspecto_familiar:
        'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    },
    {
      id: 50,
      nome: 'Karisa',
      telefone: '(209) 3581360',
      data_de_nascimento: '04/11/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(202) 9268979',
      cad_unico: '8441565856',
      rua: '8576 Monument Lane',
      cidade: 'Fresno',
      estado: 'California',
      aspecto_familiar:
        'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
    },
    {
      id: 51,
      nome: 'Ingrim',
      telefone: '(517) 7652982',
      data_de_nascimento: '24/10/2019',
      genero: 'Male',
      bairro: 'MI',
      celular: '(203) 6383660',
      cad_unico: '8476623747',
      rua: '086 Washington Street',
      cidade: 'Lansing',
      estado: 'Michigan',
      aspecto_familiar:
        'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',
    },
    {
      id: 52,
      nome: 'Micheil',
      telefone: '(702) 8551592',
      data_de_nascimento: '09/06/2019',
      genero: 'Male',
      bairro: 'NV',
      celular: '(917) 1204348',
      cad_unico: '3458029044',
      rua: '35215 Westerfield Point',
      cidade: 'Las Vegas',
      estado: 'Nevada',
      aspecto_familiar: 'Morbi quis tortor id nulla ultrices aliquet.',
    },
    {
      id: 53,
      nome: 'Filip',
      telefone: '(810) 7081650',
      data_de_nascimento: '13/02/2020',
      genero: 'Male',
      bairro: 'MI',
      celular: '(508) 3743086',
      cad_unico: '3893075283',
      rua: '10 Dryden Avenue',
      cidade: 'Flint',
      estado: 'Michigan',
      aspecto_familiar: 'Etiam justo.',
    },
    {
      id: 54,
      nome: 'Holt',
      telefone: '(601) 5258520',
      data_de_nascimento: '18/12/2019',
      genero: 'Male',
      bairro: 'MS',
      celular: '(720) 1867062',
      cad_unico: '6767397814',
      rua: '6205 Parkside Street',
      cidade: 'Jackson',
      estado: 'Mississippi',
      aspecto_familiar:
        'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
    },
    {
      id: 55,
      nome: 'Delainey',
      telefone: '(202) 8558392',
      data_de_nascimento: '02/11/2019',
      genero: 'Male',
      bairro: 'DC',
      celular: '(513) 5532379',
      cad_unico: '7077214818',
      rua: '33 Service Plaza',
      cidade: 'Washington',
      estado: 'District of Columbia',
      aspecto_familiar:
        'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    },
    {
      id: 56,
      nome: 'Kakalina',
      telefone: '(352) 8795381',
      data_de_nascimento: '24/03/2020',
      genero: 'Female',
      bairro: 'FL',
      celular: '(612) 8834523',
      cad_unico: '4493391677',
      rua: '6992 Lyons Parkway',
      cidade: 'Gainesville',
      estado: 'Florida',
      aspecto_familiar:
        'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    },
    {
      id: 57,
      nome: 'Ephrayim',
      telefone: '(209) 9451349',
      data_de_nascimento: '02/01/2020',
      genero: 'Male',
      bairro: 'CA',
      celular: '(815) 8306865',
      cad_unico: '0445789077',
      rua: '55 Donald Parkway',
      cidade: 'Stockton',
      estado: 'California',
      aspecto_familiar:
        'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    },
    {
      id: 58,
      nome: 'Engelbert',
      telefone: '(614) 5785571',
      data_de_nascimento: '16/09/2019',
      genero: 'Male',
      bairro: 'OH',
      celular: '(410) 6005293',
      cad_unico: '5514336026',
      rua: '07 Talisman Park',
      cidade: 'Columbus',
      estado: 'Ohio',
      aspecto_familiar:
        'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    },
    {
      id: 59,
      nome: 'Lucien',
      telefone: '(718) 1090938',
      data_de_nascimento: '04/04/2020',
      genero: 'Male',
      bairro: 'NY',
      celular: '(212) 6959097',
      cad_unico: '8231124071',
      rua: '07355 Towne Plaza',
      cidade: 'Staten Island',
      estado: 'New York',
      aspecto_familiar: 'Etiam justo. Etiam pretium iaculis justo.',
    },
    {
      id: 60,
      nome: 'Chaim',
      telefone: '(337) 9379651',
      data_de_nascimento: '25/12/2019',
      genero: 'Male',
      bairro: 'LA',
      celular: '(806) 8092898',
      cad_unico: '9393953236',
      rua: '4 Dexter Lane',
      cidade: 'Lake Charles',
      estado: 'Louisiana',
      aspecto_familiar:
        'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',
    },
    {
      id: 61,
      nome: 'Dionysus',
      telefone: '(336) 8547703',
      data_de_nascimento: '14/10/2019',
      genero: 'Male',
      bairro: 'NC',
      celular: '(785) 9597446',
      cad_unico: '3073337601',
      rua: '1 Kipling Drive',
      cidade: 'Greensboro',
      estado: 'North Carolina',
      aspecto_familiar:
        'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',
    },
    {
      id: 62,
      nome: 'Vallie',
      telefone: '(626) 2677807',
      data_de_nascimento: '20/03/2020',
      genero: 'Female',
      bairro: 'CA',
      celular: '(609) 9476364',
      cad_unico: '9424820666',
      rua: '22 Leroy Circle',
      cidade: 'Los Angeles',
      estado: 'California',
      aspecto_familiar:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.',
    },
    {
      id: 63,
      nome: 'Reube',
      telefone: '(480) 5849893',
      data_de_nascimento: '23/05/2019',
      genero: 'Male',
      bairro: 'AZ',
      celular: '(517) 2703825',
      cad_unico: '6363959101',
      rua: '1846 Kennedy Plaza',
      cidade: 'Phoenix',
      estado: 'Arizona',
      aspecto_familiar:
        'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.',
    },
    {
      id: 64,
      nome: 'Michell',
      telefone: '(808) 9996263',
      data_de_nascimento: '26/01/2020',
      genero: 'Female',
      bairro: 'HI',
      celular: '(615) 1017695',
      cad_unico: '7743789098',
      rua: '284 Johnson Circle',
      cidade: 'Honolulu',
      estado: 'Hawaii',
      aspecto_familiar: 'Etiam faucibus cursus urna.',
    },
    {
      id: 65,
      nome: 'Cassandry',
      telefone: '(509) 9012725',
      data_de_nascimento: '16/08/2019',
      genero: 'Female',
      bairro: 'WA',
      celular: '(405) 2076227',
      cad_unico: '9002668430',
      rua: '8581 Waywood Terrace',
      cidade: 'Spokane',
      estado: 'Washington',
      aspecto_familiar: 'Cras non velit nec nisi vulputate nonummy.',
    },
    {
      id: 66,
      nome: 'Garvy',
      telefone: '(717) 2997259',
      data_de_nascimento: '27/04/2019',
      genero: 'Male',
      bairro: 'PA',
      celular: '(614) 5056694',
      cad_unico: '4775429884',
      rua: '9 Fairview Lane',
      cidade: 'Lancaster',
      estado: 'Pennsylvania',
      aspecto_familiar: 'Integer a nibh.',
    },
    {
      id: 67,
      nome: 'Patricio',
      telefone: '(513) 6115159',
      data_de_nascimento: '17/05/2019',
      genero: 'Male',
      bairro: 'OH',
      celular: '(713) 1978866',
      cad_unico: '2964558906',
      rua: '95 3rd Plaza',
      cidade: 'Dayton',
      estado: 'Ohio',
      aspecto_familiar:
        'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    },
    {
      id: 68,
      nome: 'Stewart',
      telefone: '(915) 1780704',
      data_de_nascimento: '07/03/2020',
      genero: 'Male',
      bairro: 'TX',
      celular: '(816) 1320251',
      cad_unico: '0529219425',
      rua: '81 Annamark Alley',
      cidade: 'El Paso',
      estado: 'Texas',
      aspecto_familiar:
        'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
    },
    {
      id: 69,
      nome: 'Christyna',
      telefone: '(816) 1112898',
      data_de_nascimento: '01/03/2020',
      genero: 'Female',
      bairro: 'MO',
      celular: '(717) 3547418',
      cad_unico: '6639673304',
      rua: '213 Morningstar Alley',
      cidade: 'Kansas City',
      estado: 'Missouri',
      aspecto_familiar:
        'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
    },
    {
      id: 70,
      nome: 'Svend',
      telefone: '(786) 1046998',
      data_de_nascimento: '30/03/2020',
      genero: 'Male',
      bairro: 'FL',
      celular: '(312) 7715144',
      cad_unico: '3231107369',
      rua: '025 Lotheville Road',
      cidade: 'Miami',
      estado: 'Florida',
      aspecto_familiar:
        'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',
    },
    {
      id: 71,
      nome: 'Shari',
      telefone: '(502) 2296168',
      data_de_nascimento: '11/07/2019',
      genero: 'Female',
      bairro: 'KY',
      celular: '(973) 1203493',
      cad_unico: '3185657985',
      rua: '1167 Gale Avenue',
      cidade: 'Louisville',
      estado: 'Kentucky',
      aspecto_familiar:
        'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    },
    {
      id: 72,
      nome: 'Sibilla',
      telefone: '(410) 6051744',
      data_de_nascimento: '15/05/2019',
      genero: 'Female',
      bairro: 'MD',
      celular: '(937) 9734901',
      cad_unico: '4463301483',
      rua: '8 Summer Ridge Crossing',
      cidade: 'Baltimore',
      estado: 'Maryland',
      aspecto_familiar:
        'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    },
    {
      id: 73,
      nome: 'Jobi',
      telefone: '(253) 4504473',
      data_de_nascimento: '08/04/2019',
      genero: 'Female',
      bairro: 'WA',
      celular: '(540) 7672241',
      cad_unico: '3402122006',
      rua: '567 Blaine Junction',
      cidade: 'Tacoma',
      estado: 'Washington',
      aspecto_familiar:
        'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    },
    {
      id: 74,
      nome: 'Vale',
      telefone: '(305) 1782079',
      data_de_nascimento: '19/05/2019',
      genero: 'Male',
      bairro: 'FL',
      celular: '(772) 8408435',
      cad_unico: '2944845934',
      rua: '5 Portage Drive',
      cidade: 'Naples',
      estado: 'Florida',
      aspecto_familiar: 'Praesent blandit lacinia erat.',
    },
    {
      id: 75,
      nome: 'Delila',
      telefone: '(404) 4046012',
      data_de_nascimento: '12/09/2019',
      genero: 'Female',
      bairro: 'GA',
      celular: '(602) 7825518',
      cad_unico: '8063095510',
      rua: '134 Hooker Road',
      cidade: 'Atlanta',
      estado: 'Georgia',
      aspecto_familiar:
        'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    },
    {
      id: 76,
      nome: 'Justin',
      telefone: '(843) 6960430',
      data_de_nascimento: '03/10/2019',
      genero: 'Male',
      bairro: 'SC',
      celular: '(573) 8719004',
      cad_unico: '1907318127',
      rua: '0650 Dorton Alley',
      cidade: 'Charleston',
      estado: 'South Carolina',
      aspecto_familiar:
        'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.',
    },
    {
      id: 77,
      nome: 'Barbette',
      telefone: '(518) 1873528',
      data_de_nascimento: '27/03/2020',
      genero: 'Female',
      bairro: 'NY',
      celular: '(202) 2833283',
      cad_unico: '2424784663',
      rua: '4091 Sommers Avenue',
      cidade: 'Schenectady',
      estado: 'New York',
      aspecto_familiar:
        'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
    },
    {
      id: 78,
      nome: 'Levi',
      telefone: '(336) 6421088',
      data_de_nascimento: '19/09/2019',
      genero: 'Male',
      bairro: 'NC',
      celular: '(813) 8834848',
      cad_unico: '8976736710',
      rua: '1919 Sloan Terrace',
      cidade: 'Winston Salem',
      estado: 'North Carolina',
      aspecto_familiar:
        'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',
    },
    {
      id: 79,
      nome: 'Sarah',
      telefone: '(202) 4699594',
      data_de_nascimento: '31/05/2019',
      genero: 'Female',
      bairro: 'DC',
      celular: '(480) 6839085',
      cad_unico: '5830847280',
      rua: '19 Veith Lane',
      cidade: 'Washington',
      estado: 'District of Columbia',
      aspecto_familiar:
        'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    },
    {
      id: 80,
      nome: 'Wittie',
      telefone: '(619) 1543961',
      data_de_nascimento: '12/03/2020',
      genero: 'Male',
      bairro: 'CA',
      celular: '(937) 1483711',
      cad_unico: '2670019943',
      rua: '976 Ridgeview Terrace',
      cidade: 'San Diego',
      estado: 'California',
      aspecto_familiar:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    },
    {
      id: 81,
      nome: 'Blythe',
      telefone: '(504) 4583239',
      data_de_nascimento: '23/08/2019',
      genero: 'Female',
      bairro: 'LA',
      celular: '(864) 7227594',
      cad_unico: '6631196159',
      rua: '796 Briar Crest Street',
      cidade: 'New Orleans',
      estado: 'Louisiana',
      aspecto_familiar:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.',
    },
    {
      id: 82,
      nome: 'Amanda',
      telefone: '(253) 9698816',
      data_de_nascimento: '04/08/2019',
      genero: 'Female',
      bairro: 'WA',
      celular: '(971) 9234029',
      cad_unico: '7943716094',
      rua: '3190 Memorial Place',
      cidade: 'Tacoma',
      estado: 'Washington',
      aspecto_familiar:
        'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
    },
    {
      id: 83,
      nome: 'Matty',
      telefone: '(907) 1541740',
      data_de_nascimento: '11/09/2019',
      genero: 'Male',
      bairro: 'AK',
      celular: '(408) 1187935',
      cad_unico: '8384153973',
      rua: '35 Talmadge Drive',
      cidade: 'Fairbanks',
      estado: 'Alaska',
      aspecto_familiar:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
    },
    {
      id: 84,
      nome: 'Ardelia',
      telefone: '(706) 6863545',
      data_de_nascimento: '23/01/2020',
      genero: 'Female',
      bairro: 'GA',
      celular: '(304) 6325597',
      cad_unico: '8453973946',
      rua: '7349 Heath Drive',
      cidade: 'Cumming',
      estado: 'Georgia',
      aspecto_familiar:
        'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    },
    {
      id: 85,
      nome: 'Farly',
      telefone: '(585) 7482085',
      data_de_nascimento: '10/08/2019',
      genero: 'Male',
      bairro: 'NY',
      celular: '(912) 2005233',
      cad_unico: '4227638844',
      rua: '15079 Bayside Terrace',
      cidade: 'Rochester',
      estado: 'New York',
      aspecto_familiar:
        'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',
    },
    {
      id: 86,
      nome: 'Marion',
      telefone: '(786) 7513963',
      data_de_nascimento: '30/04/2019',
      genero: 'Male',
      bairro: 'FL',
      celular: '(513) 7883868',
      cad_unico: '1822211018',
      rua: '49882 3rd Court',
      cidade: 'Miami',
      estado: 'Florida',
      aspecto_familiar:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.',
    },
    {
      id: 87,
      nome: 'Jacenta',
      telefone: '(256) 6551649',
      data_de_nascimento: '31/01/2020',
      genero: 'Female',
      bairro: 'AL',
      celular: '(773) 7768006',
      cad_unico: '8749310925',
      rua: '5 Steensland Lane',
      cidade: 'Huntsville',
      estado: 'Alabama',
      aspecto_familiar:
        'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
    },
    {
      id: 88,
      nome: 'Bastien',
      telefone: '(816) 2084619',
      data_de_nascimento: '30/12/2019',
      genero: 'Male',
      bairro: 'MO',
      celular: '(617) 4454124',
      cad_unico: '9367583214',
      rua: '497 Bashford Trail',
      cidade: 'Kansas City',
      estado: 'Missouri',
      aspecto_familiar:
        'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.',
    },
    {
      id: 89,
      nome: 'Stephannie',
      telefone: '(313) 9155707',
      data_de_nascimento: '26/03/2020',
      genero: 'Female',
      bairro: 'MI',
      celular: '(212) 6534321',
      cad_unico: '7856872705',
      rua: '017 Sunbrook Lane',
      cidade: 'Detroit',
      estado: 'Michigan',
      aspecto_familiar:
        'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    },
    {
      id: 90,
      nome: 'Tallie',
      telefone: '(601) 2197167',
      data_de_nascimento: '10/09/2019',
      genero: 'Male',
      bairro: 'MS',
      celular: '(310) 9391392',
      cad_unico: '5070837427',
      rua: '69 Meadow Ridge Road',
      cidade: 'Hattiesburg',
      estado: 'Mississippi',
      aspecto_familiar:
        'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.',
    },
    {
      id: 91,
      nome: 'Bernete',
      telefone: '(650) 8756347',
      data_de_nascimento: '11/08/2019',
      genero: 'Female',
      bairro: 'CA',
      celular: '(305) 2140404',
      cad_unico: '2968828029',
      rua: '940 Lighthouse Bay Lane',
      cidade: 'Redwood City',
      estado: 'California',
      aspecto_familiar:
        'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
    },
    {
      id: 92,
      nome: 'Carmelle',
      telefone: '(763) 8262033',
      data_de_nascimento: '28/08/2019',
      genero: 'Female',
      bairro: 'MN',
      celular: '(775) 1352136',
      cad_unico: '9719401443',
      rua: '559 Hauk Crossing',
      cidade: 'Minneapolis',
      estado: 'Minnesota',
      aspecto_familiar:
        'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
    },
    {
      id: 93,
      nome: 'Gus',
      telefone: '(804) 3098331',
      data_de_nascimento: '10/10/2019',
      genero: 'Female',
      bairro: 'VA',
      celular: '(504) 5772355',
      cad_unico: '7101594344',
      rua: '2 Anhalt Park',
      cidade: 'Richmond',
      estado: 'Virginia',
      aspecto_familiar: 'Proin risus.',
    },
    {
      id: 94,
      nome: 'Fee',
      telefone: '(502) 5466936',
      data_de_nascimento: '20/11/2019',
      genero: 'Male',
      bairro: 'KY',
      celular: '(727) 1916811',
      cad_unico: '5122467951',
      rua: '7 Dayton Place',
      cidade: 'Louisville',
      estado: 'Kentucky',
      aspecto_familiar:
        'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    },
    {
      id: 95,
      nome: 'Carline',
      telefone: '(361) 4272851',
      data_de_nascimento: '22/06/2019',
      genero: 'Female',
      bairro: 'TX',
      celular: '(212) 6952292',
      cad_unico: '2236306067',
      rua: '10 Browning Trail',
      cidade: 'Corpus Christi',
      estado: 'Texas',
      aspecto_familiar:
        'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',
    },
    {
      id: 96,
      nome: 'Bee',
      telefone: '(330) 5971603',
      data_de_nascimento: '19/03/2020',
      genero: 'Female',
      bairro: 'OH',
      celular: '(901) 5413632',
      cad_unico: '6513406226',
      rua: '131 Monterey Center',
      cidade: 'Youngstown',
      estado: 'Ohio',
      aspecto_familiar: 'Morbi a ipsum. Integer a nibh. In quis justo.',
    },
    {
      id: 97,
      nome: 'Starla',
      telefone: '(478) 8183244',
      data_de_nascimento: '23/02/2020',
      genero: 'Female',
      bairro: 'GA',
      celular: '(773) 7740972',
      cad_unico: '2767073101',
      rua: '60146 Pleasure Trail',
      cidade: 'Macon',
      estado: 'Georgia',
      aspecto_familiar:
        'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
    },
    {
      id: 98,
      nome: 'Clayson',
      telefone: '(805) 2553283',
      data_de_nascimento: '03/12/2019',
      genero: 'Male',
      bairro: 'CA',
      celular: '(405) 8729745',
      cad_unico: '8443964871',
      rua: '5844 Burning Wood Pass',
      cidade: 'Santa Barbara',
      estado: 'California',
      aspecto_familiar:
        'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
    },
    {
      id: 99,
      nome: 'Brigham',
      telefone: '(713) 2852250',
      data_de_nascimento: '07/11/2019',
      genero: 'Male',
      bairro: 'TX',
      celular: '(858) 2816017',
      cad_unico: '5752175372',
      rua: '47075 Commercial Crossing',
      cidade: 'Houston',
      estado: 'Texas',
      aspecto_familiar:
        'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
    },
    {
      id: 100,
      nome: 'Abby',
      telefone: '(773) 8319636',
      data_de_nascimento: '19/05/2019',
      genero: 'Female',
      bairro: 'IL',
      celular: '(239) 9139941',
      cad_unico: '6831836739',
      rua: '655 Esch Crossing',
      cidade: 'Chicago',
      estado: 'Illinois',
      aspecto_familiar:
        'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    },
  ]);

  const tableRef = useRef(null);

  const query = new URLSearchParams(useLocation().search);
  const name = query.get('name');

  function handleClose() {
    setOpen(false);
    setGroupCreate(false);
  }

  function handleOpen() {
    if (selected < 2) return;
    setOpen(true);
  }

  function handleSelectDataContacts(rows) {
    let q = 0;
    const newGroups = dataContacts.map((item) => {
      let ck = false;
      if (rows.filter((row) => item.id === row.id).length) ck = true;
      if (ck) q++;
      return { ...item, tableData: { checked: ck } };
    });
    setSelected(q);
    setDataContacts([...newGroups]);
  }

  return (
    <Container>
      {name && (
        <Link to="/group">
          <BackLink>
            <MdArrowBack size="24" color="rgba(0, 0, 0, 0.54)" /> {name}
          </BackLink>
        </Link>
      )}
      <GridActions>
        <Actions selected={selected}>Exportar Excel</Actions>
        <Actions selected={selected > 1} onClick={handleOpen}>
          Criar Grupo
        </Actions>
        <Actions selected={selected}>Excluir</Actions>
      </GridActions>
      <MaterialTable
        ref={tableRef}
        title="Lista de Contatos"
        columns={[
          { title: 'Nome', field: 'nome' },
          { title: 'Telefone', field: 'telefone' },
          { title: 'Data de Nascimento', field: 'data_de_nascimento' },
          { title: 'Bairro', field: 'bairro' },
          { title: 'Genero', field: 'genero' },
          {
            title: 'Mais Detalhes',
            render: (row) => (
              <Link to={`/contact/edit?name=${row.nome}`}>
                <LinkMore>Mais dados</LinkMore>
              </Link>
            ),
          },
        ]}
        data={dataContacts}
        options={{
          search: true,
          selection: true,
          pageSize: 10,
        }}
        onSelectionChange={handleSelectDataContacts}
        localization={{
          pagination: {
            labelDisplayedRows: '{from}-{to} de {count}',
            labelRowsSelect: 'por página',
          },
          toolbar: {
            nRowsSelected: '{0} selecionado(s)',
            searchPlaceholder: 'Pesquisar',
          },
          header: { actions: 'Ações' },
          body: {
            emptyDataSourceMessage: 'Nenhuma informação',
            filterRow: { filterTooltip: 'Filtro' },
          },
        }}
      />
      <Modal open={open} onClose={handleClose}>
        <ModalContent>
          {!groupCreate ? (
            <>
              <ModalTitle>Criar Grupo</ModalTitle>
              <ModalInput placeholder="Nome do Grupo" />
              <ModalActions>
                <ModalCancel onClick={handleClose}>CANCELAR</ModalCancel>
                <ModalConfirm
                  onClick={() => {
                    setGroupCreate(true);
                  }}
                >
                  CRIAR
                </ModalConfirm>
              </ModalActions>
            </>
          ) : (
            <>
              <ModalTitle>Sucesso!</ModalTitle>
              <ModalDesc>Seu grupo está salvo na Lista de Grupos.</ModalDesc>
              <ModalActions>
                <Link to="/group">
                  <ModalCancel>VER AGORA</ModalCancel>
                </Link>
                <ModalConfirm onClick={handleClose}>FECHAR</ModalConfirm>
              </ModalActions>
            </>
          )}
        </ModalContent>
      </Modal>
    </Container>
  );
}
